function init(self)
	self.a = 0.0
	self.b = 0.0
	self.a_amp = 0.01
	self.b_amp = -0.01
	send_camera_state(self)

	msg.post(".", "acquire_input_focus")
end

function send_camera_state(self)
	msg.post("@render:", "camera_state", { a = self.a, b = self.b })
end

function update(self, dt)
	send_camera_state(self)
end


function on_input(self, action_id, action)
	if action_id == hash("touch") then
		self.a = self.a + action.dx * self.a_amp
		self.b = self.b + action.dy * self.b_amp
	end
end
